$f = "C:\Users\CTech Electronics\Desktop\Steroid\Steroiden\astro-steroid\src\i18n\translations.ts"
$content = [IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$before = ([regex]::Matches($content, '[Pp]eptid')).Count
Write-Host "Before: $before matches"

# ===== NL (Dutch) compound words =====
$content = $content -replace "onderzoekspeptiden", "anabole steroïden"
$content = $content -replace "Onderzoekspeptiden", "Anabole steroïden"
$content = $content -replace "onderzoekspeptide", "anabole steroïde"
$content = $content -replace "Onderzoekspeptide", "Anabole steroïde"
$content = $content -replace "onderzoekpeptiden", "anabole steroïden"
$content = $content -replace "Onderzoekpeptiden", "Anabole steroïden"
$content = $content -replace "peptideonderzoek", "steroïdenonderzoek"
$content = $content -replace "Peptideonderzoek", "Steroïdenonderzoek"
$content = $content -replace "peptidebundels", "steroïdenstacks"
$content = $content -replace "Peptidebundels", "Steroïdenstacks"
$content = $content -replace "peptidecombinaties", "steroïdecombinaties"
$content = $content -replace "peptidebindinge", "chemische bindinge"
$content = $content -replace "peptidezuiverheid", "productzuiverheid"
$content = $content -replace "peptidekwaliteit", "productkwaliteit"
$content = $content -replace "peptidebehoeften", "steroïdenbehoeften"
$content = $content -replace "peptide-identiteit", "productidentiteit"
$content = $content -replace "peptide-integriteit", "productintegriteit"
$content = $content -replace "peptide-hanteringsprotocollen", "steroïden-gebruiksprotocollen"
$content = $content -replace "peptideleverancier", "steroïdenleverancier"
$content = $content -replace "peptidebundel", "steroïdenstack"

# NL phrases
$content = $content -replace "Zoek peptiden", "Zoek steroïden"
$content = $content -replace "peptiden kopen", "steroïden kopen"
$content = $content -replace "Peptiden kopen", "Steroïden kopen"
$content = $content -replace "Peptiden Kopen", "Steroïden Kopen"
$content = $content -replace "Peptiden Online", "Steroïden Online"
$content = $content -replace "peptiden bekijken", "steroïden bekijken"
$content = $content -replace "Peptiden bekijken", "Steroïden bekijken"
$content = $content -replace "peptiden ondergaan", "steroïden ondergaan"
$content = $content -replace "peptiden worden", "steroïden worden"
$content = $content -replace "Alle peptiden", "Alle steroïden"
$content = $content -replace "alle peptiden", "alle steroïden"
$content = $content -replace "Shop Peptiden", "Shop Steroïden"
$content = $content -replace "Blader door peptiden", "Blader door steroïden"
$content = $content -replace "peptiden anders", "steroïden anders"
$content = $content -replace "peptiden bewaren", "steroïden bewaren"
$content = $content -replace "Bekijk peptiden", "Bekijk steroïden"
$content = $content -replace "Bekijk Alle Peptiden", "Bekijk Alle Steroïden"
$content = $content -replace "onze peptiden", "onze steroïden"
$content = $content -replace "jullie peptiden", "jullie steroïden"
$content = $content -replace "batch peptiden", "batch steroïden"
$content = $content -replace "Populair onderzoekspeptide", "Populair steroïde"
# Remaining NL standalone peptide/peptiden
$content = $content -replace "peptiden", "steroïden"
$content = $content -replace "Peptiden", "Steroïden"
$content = $content -replace "(?<!')peptide(?!')", "steroïde"

# ===== DE (German) compound words =====
$content = $content -replace "Forschungspeptide", "anabole Steroide"
$content = $content -replace "forschungspeptide", "anabole Steroide"
$content = $content -replace "Forschungspeptiden", "anabole Steroide"
$content = $content -replace "Peptidforschung", "Steroidforschung"
$content = $content -replace "Peptidbindungen", "chemische Bindungen"
$content = $content -replace "Peptidsynthese", "Steroidsynthese"
$content = $content -replace "Peptidkette", "Steroidverbindung"
$content = $content -replace "Peptidstruktur", "Steroidstruktur"
$content = $content -replace "Peptidqualität", "Produktqualität"
$content = $content -replace "Peptidreinheit", "Produktreinheit"
$content = $content -replace "Peptididentität", "Produktidentität"
$content = $content -replace "Peptidintegrität", "Produktintegrität"
$content = $content -replace "Peptidlieferant", "Steroidlieferant"
$content = $content -replace "Peptidbündel", "Steroid-Stacks"
$content = $content -replace "Peptidkombinationen", "Steroidkombinationen"
$content = $content -replace "Peptidlösungen", "Steroidlösungen"
$content = $content -replace "Peptidprotokoll", "Steroidprotokoll"
$content = $content -replace "Peptidanbieter", "Steroidanbieter"

# DE phrases
$content = $content -replace "Peptide kaufen", "Steroide kaufen"
$content = $content -replace "peptide kaufen", "steroide kaufen"
$content = $content -replace "Peptide sicher kaufen", "Steroide sicher kaufen"
$content = $content -replace "Peptide suchen", "Steroide suchen"
$content = $content -replace "Alle Peptide", "Alle Steroide"
$content = $content -replace "alle Peptide", "alle Steroide"
$content = $content -replace "unsere Peptide", "unsere Steroide"
$content = $content -replace "Unsere Peptide", "Unsere Steroide"
$content = $content -replace "Shop Peptide", "Shop Steroide"
$content = $content -replace "Peptide durchsuchen", "Steroide durchsuchen"
$content = $content -replace "Peptide ansehen", "Steroide ansehen"
$content = $content -replace "Peptide bestellen", "Steroide bestellen"
$content = $content -replace "Premium-Peptide", "Premium-Steroide"
$content = $content -replace "premium Peptide", "Premium-Steroide"
$content = $content -replace "hochwertige Peptide", "hochwertige Steroide"
$content = $content -replace "Peptide Online", "Steroide Online"
$content = $content -replace "Peptide Kaufen", "Steroide Kaufen"
# Remaining DE standalone
$content = $content -replace "(?<![a-zäöü])Peptide(?![a-zäöü])", "Steroide"
$content = $content -replace "(?<![a-zäöü])Peptid(?![a-zäöü])", "Steroid"

# ===== FR (French) =====
$content = $content -replace "peptides de recherche", "stéroïdes anabolisants"
$content = $content -replace "Peptides de recherche", "Stéroïdes anabolisants"
$content = $content -replace "peptides de qualité", "stéroïdes de qualité"
$content = $content -replace "recherche peptidique", "recherche stéroïdique"
$content = $content -replace "liaisons peptidiques", "liaisons chimiques"
$content = $content -replace "chaînes peptidiques", "composés stéroïdiques"
$content = $content -replace "lots de peptides", "lots de stéroïdes"
$content = $content -replace "pureté des peptides", "pureté des stéroïdes"
$content = $content -replace "fournisseur de peptides", "fournisseur de stéroïdes"
$content = $content -replace "Fournisseur de peptides", "Fournisseur de stéroïdes"
$content = $content -replace "Acheter des peptides", "Acheter des stéroïdes"
$content = $content -replace "acheter des peptides", "acheter des stéroïdes"
$content = $content -replace "Rechercher des peptides", "Rechercher des stéroïdes"
$content = $content -replace "Rechercher peptides", "Rechercher stéroïdes"
$content = $content -replace "Tous les peptides", "Tous les stéroïdes"
$content = $content -replace "tous les peptides", "tous les stéroïdes"
$content = $content -replace "nos peptides", "nos stéroïdes"
$content = $content -replace "Shop Peptides", "Shop Stéroïdes"
$content = $content -replace "Parcourir les peptides", "Parcourir les stéroïdes"
$content = $content -replace "Peptides en ligne", "Stéroïdes en ligne"
$content = $content -replace "Voir tous les peptides", "Voir tous les stéroïdes"
$content = $content -replace "Voir les peptides", "Voir les stéroïdes"
$content = $content -replace "vos peptides", "vos stéroïdes"
$content = $content -replace "ces peptides", "ces stéroïdes"
$content = $content -replace "Ces peptides", "Ces stéroïdes"
# FR remaining standalone - be careful with word boundaries
$content = $content -replace "les peptides", "les stéroïdes"
$content = $content -replace "Les peptides", "Les stéroïdes"
$content = $content -replace "des peptides", "des stéroïdes"
$content = $content -replace "Des peptides", "Des stéroïdes"
$content = $content -replace "aux peptides", "aux stéroïdes"
$content = $content -replace "peptides ", "stéroïdes "
$content = $content -replace "Peptides ", "Stéroïdes "

# ===== ES (Spanish) =====
$content = $content -replace "péptidos de investigación", "esteroides anabólicos"
$content = $content -replace "Péptidos de investigación", "Esteroides anabólicos"
$content = $content -replace "péptidos de calidad", "esteroides de calidad"
$content = $content -replace "péptidos sintéticos", "esteroides sintéticos"
$content = $content -replace "enlaces peptídicos", "enlaces químicos"
$content = $content -replace "cadenas peptídicas", "compuestos esteroideos"
$content = $content -replace "proveedor de péptidos", "proveedor de esteroides"
$content = $content -replace "Proveedor de péptidos", "Proveedor de esteroides"
$content = $content -replace "Comprar péptidos", "Comprar esteroides"
$content = $content -replace "comprar péptidos", "comprar esteroides"
$content = $content -replace "Buscar péptidos", "Buscar esteroides"
$content = $content -replace "buscar péptidos", "buscar esteroides"
$content = $content -replace "Todos los péptidos", "Todos los esteroides"
$content = $content -replace "todos los péptidos", "todos los esteroides"
$content = $content -replace "nuestros péptidos", "nuestros esteroides"
$content = $content -replace "Nuestros péptidos", "Nuestros esteroides"
$content = $content -replace "los péptidos", "los esteroides"
$content = $content -replace "Los péptidos", "Los esteroides"
$content = $content -replace "péptidos online", "esteroides online"
$content = $content -replace "Péptidos online", "Esteroides online"
$content = $content -replace "Péptidos Online", "Esteroides Online"
$content = $content -replace "Ver todos los péptidos", "Ver todos los esteroides"
$content = $content -replace "Ver péptidos", "Ver esteroides"
$content = $content -replace "Explorar péptidos", "Explorar esteroides"
$content = $content -replace "explorar péptidos", "explorar esteroides"
# ES remaining standalone
$content = $content -replace "péptidos", "esteroides"
$content = $content -replace "Péptidos", "Esteroides"
$content = $content -replace "péptido", "esteroide"
$content = $content -replace "Péptido", "Esteroide"
$content = $content -replace "peptídico", "esteroideo"
$content = $content -replace "peptídica", "esteroidal"

# ===== IT (Italian) =====
$content = $content -replace "peptidi di ricerca", "steroidi anabolizzanti"
$content = $content -replace "Peptidi di ricerca", "Steroidi anabolizzanti"
$content = $content -replace "peptidi di qualità", "steroidi di qualità"
$content = $content -replace "legami peptidici", "legami chimici"
$content = $content -replace "catene peptidiche", "composti steroidei"
$content = $content -replace "fornitore di peptidi", "fornitore di steroidi"
$content = $content -replace "Fornitore di peptidi", "Fornitore di steroidi"
$content = $content -replace "Acquista peptidi", "Acquista steroidi"
$content = $content -replace "acquista peptidi", "acquista steroidi"
$content = $content -replace "Acquistare peptidi", "Acquistare steroidi"
$content = $content -replace "acquistare peptidi", "acquistare steroidi"
$content = $content -replace "Cerca peptidi", "Cerca steroidi"
$content = $content -replace "cerca peptidi", "cerca steroidi"
$content = $content -replace "Tutti i peptidi", "Tutti gli steroidi"
$content = $content -replace "tutti i peptidi", "tutti gli steroidi"
$content = $content -replace "i nostri peptidi", "i nostri steroidi"
$content = $content -replace "I nostri peptidi", "I nostri steroidi"
$content = $content -replace "i peptidi", "gli steroidi"
$content = $content -replace "I peptidi", "Gli steroidi"
$content = $content -replace "dei peptidi", "degli steroidi"
$content = $content -replace "Shop Peptidi", "Shop Steroidi"
$content = $content -replace "Sfoglia peptidi", "Sfoglia steroidi"
$content = $content -replace "sfoglia peptidi", "sfoglia steroidi"
$content = $content -replace "Vedi tutti i peptidi", "Vedi tutti gli steroidi"
$content = $content -replace "Peptidi Online", "Steroidi Online"
# IT remaining standalone
$content = $content -replace "peptidi", "steroidi"
$content = $content -replace "Peptidi", "Steroidi"
$content = $content -replace "peptide", "steroide"
$content = $content -replace "peptidico", "steroideo"
$content = $content -replace "peptidica", "steroidea"
$content = $content -replace "peptidici", "steroidei"
$content = $content -replace "peptidiche", "steroidee"

# ===== RU (Russian) =====
$content = $content -replace "исследовательские пептиды", "анаболические стероиды" 
$content = $content -replace "Исследовательские пептиды", "Анаболические стероиды"
$content = $content -replace "исследовательских пептидов", "анаболических стероидов"
$content = $content -replace "пептидных связей", "химических связей"
$content = $content -replace "пептидные цепи", "стероидные соединения"
$content = $content -replace "чистота пептидов", "чистота стероидов"
$content = $content -replace "поставщик пептидов", "поставщик стероидов"
$content = $content -replace "Поставщик пептидов", "Поставщик стероидов"
$content = $content -replace "Купить пептиды", "Купить стероиды"
$content = $content -replace "купить пептиды", "купить стероиды"
$content = $content -replace "Все пептиды", "Все стероиды"
$content = $content -replace "все пептиды", "все стероиды"
$content = $content -replace "наши пептиды", "наши стероиды"
$content = $content -replace "Наши пептиды", "Наши стероиды"
$content = $content -replace "пептиды онлайн", "стероиды онлайн"
$content = $content -replace "Пептиды Онлайн", "Стероиды Онлайн"
$content = $content -replace "пептиды для", "стероиды для"
$content = $content -replace "Пептиды для", "Стероиды для"
$content = $content -replace "Искать пептиды", "Искать стероиды"
$content = $content -replace "Посмотреть все пептиды", "Посмотреть все стероиды"
$content = $content -replace "Смотреть пептиды", "Смотреть стероиды"
# RU remaining standalone
$content = $content -replace "пептиды", "стероиды"
$content = $content -replace "Пептиды", "Стероиды"
$content = $content -replace "пептидов", "стероидов"
$content = $content -replace "Пептидов", "Стероидов"
$content = $content -replace "пептидами", "стероидами"
$content = $content -replace "пептидам", "стероидам"
$content = $content -replace "пептиде", "стероиде"
$content = $content -replace "пептида", "стероида"
$content = $content -replace "пептид", "стероид"
$content = $content -replace "Пептид", "Стероид"

$after = ([regex]::Matches($content, '[Pp]eptid')).Count
Write-Host "After all replacements: $after matches"

[IO.File]::WriteAllText($f, $content, [System.Text.Encoding]::UTF8)
Write-Host "File saved successfully"
